baseURL = "https://agottert.github.io/werner-app/"
languageCode = "en-us"
title = "The Path to the Werner Colour App"
theme = "werner"

copyright = "&copy; <a href=\"https://github.com/agottert\">María Agustina Göttert</a> & <a href=\"https://github.com/peregrinogris\">Hernán Rodríguez Colmeiro</a> 2018"

preserveTaxonomyNames = true
[taxonomies]
tag = "tags"
category = "categories"

[params.highlight]
languages = ["go", "dockerfile"]